# Datasource - MySQL (cavosh_db)
spring.datasource.url=jdbc:mysql://localhost:3306/cavosh_db
spring.datasource.username=root
spring.datasource.password=19m26d08j
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=DmMj4/59yiawyLSJGyD6IUGuUUAE310hw1Le4iSeSYp+F8CW7db5wchC3tjAm+5Oe4h2TI0D/KJp+A2lo17kXA==
app.jwt.expiration-ms=86400000
server.port=8080