# Datasource - MySQL (cavosh_db)
spring.datasource.url=jdbc:mysql://localhost:3306/cavosh_db
spring.datasource.username=root
spring.datasource.password=19m26d08j
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080